version: '3'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/perl-Intern-Diary
    depends_on:
      - db
    environment:
      - APP_MODE=DEV
  ## for now, I should execute script manually
  db:
    image: "mysql:5.7.20"
    volumes:
      - .:/usr/src/perl-Intern-Diary
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "13306:3306"
